name: Android Build

on:
  push:
    branches:
      - "*"
      - "!badges"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    #          - macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11
          cache: gradle

      - name: Setup Android SDK
        id: "setup-android"
        uses: android-actions/setup-android@v2

      - name: Build Application
        id: "android-build"
        continue-on-error: true
        shell: bash
        #if: runner.os == 'ubuntu'
        run: |
          label="android-build"
          echo "##[set-output name=label;]${label}"
          echo sdk.dir=/usr/local/lib/android/sdk >> ApplicationCompte/local.properties
          cd ApplicationCompte && ./gradlew --no-daemon build
          res=$?
          if [ $res -eq 0 ]
          then
            retour="passing"
            color="green"
          else
            retour="failing"
            color="red"
          fi
          echo "##[set-output name=status;]${retour}"
          echo "##[set-output name=color;]${color}"

      # switch to badges branch
      - run: |
          git checkout badge_android || git checkout -b badge_android
          test -d .github/badges || mkdir -p .github/badges

      # create badge
      - name: badge
        uses: emibcn/badge-action@v1.2.1
        with:
          label: ${{ steps.android-build.outputs.label }}
          status: ${{ steps.android-build.outputs.status || 'failing' }}
          color: ${{ steps.android-build.outputs.color || 'red' }}
          path: ".github/badges/badge_android.svg"

      # commit and push badges if badges have changed
      - name: Commit changes to badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '.github/badges/badge_android.svg'
          git commit -m "Add/Update badge_android" || exit 0
          git push -f origin badge_android
